version: "3.7"
services:
  
  team_2_API:
    build: .
    image: team_2_API_image
    container_name: team_2_API_container
    ports:
      - "8002:8002"
    links:
      - team_2_postgres_app
    env_file:
      - .env

  team_2_postgres_app:
    image: postgres
    container_name: team_2_postgres_container
    ports: 
      - "5422:5432"
    env_file:
      - .env.db.docker
    volumes:
      - team_2_postgres:/var/lib/postgresql/data

volumes:
  team_2_postgres: